language: rust
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
#  - stable
#  - beta
  - nightly
#matrix:
#  allow_failures:
#    - rust: nightly
#env:
#  - CARGO_INCREMENTAL=1
#script:
#  - cargo clean
#  - cargo build
#  - cargo test
#  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo install cargo-tarpaulin
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/879ba3d8386f731f57fd
    # options: [always|never|change]
    on_success: change
    on_failure: always
    on_start: never
