[package]
name = "rsmorphy"
version = "0.3.2"
authors = ["Alexander Irbis <irbis.labs@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Morphological analyzer / inflection engine for Russian and Ukrainian (soon) languages (WIP)"
keywords = ["nlp", "inflection", "pluralize", "russian", "ukrainian"]
categories = ["text-processing", "value-formatting"]
readme = "README.md"
homepage = "https://github.com/alexander-irbis/rsmorphy"
repository = "https://github.com/alexander-irbis/rsmorphy"
documentation = "https://docs.rs/rsmorphy/"
publish = true


[dependencies]
base64              = "0.6"
flate2              = "0.2"
lazy_static         = "0.2"
log                 = "0.3"
maplit              = "0.1"
num                 = "0.1"
regex               = "0.2"
roman               = "0.1"
serde_json          = "1.0"
string_cache        = "0.5"
unicode_categories  = "0.1"

[dependencies.rsmorphy-dict-ru]
version     = "0.1"
path        = "./dict/ru"


[features]
default         = ["simd-accel"]
verbose         = []
quiet           = []
simd-accel      = ["regex/simd-accel"]
